# Generated by Django 6.0.4 on 2026-05-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicerecord_serviceauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='dmv_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='sales_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
