# Generated by Django 6.0.4 on 2026-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicerecord_dmv_fee_servicerecord_processing_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='credit_card_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
