# Generated by Django 6.0.4 on 2026-05-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='driver_license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title', 'Title'), ('bill_of_sale', 'Bill of Sale'), ('driver_license', 'Driver License'), ('insurance_id', 'Insurance ID Card'), ('mv82', 'MV82'), ('dtf802', 'DTF 802'), ('reassignments', 'Reassignments'), ('mv50', 'MV50'), ('other', 'Other docs')], max_length=30)),
                ('file', models.FileField(upload_to='service_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.servicerecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
