# Generated by Django 6.0.4 on 2026-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicerecord_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('vehicle_registration', 'Vehicle Registration'), ('registration_renewal', 'Registration Renewal'), ('get_title', 'Get A Title'), ('transfer_plate', 'Plate Transfer'), ('replace_lost_item', 'Replace lost or damage items'), ('surrender_plates', 'Surrender plates')], max_length=50),
        ),
    ]
