# Generated by Django 6.0.4 on 2026-05-02 12:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(default=core.models.generate_invite_code, max_length=20, unique=True),
        ),
    ]
