# Generated by Django 6.0.4 on 2026-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_organization_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_agents',
            field=models.IntegerField(default=5, help_text='Maximum number of agents allowed for this PSB.'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can this agent view PSB reports?'),
        ),
    ]
