# Generated by Django 6.0.4 on 2026-05-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organization_max_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_view_net_profit',
            field=models.BooleanField(default=False, help_text='Can this agent view net profit?'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CustomServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to='core.organization')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
