# Generated by Django 6.0.4 on 2026-05-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organizationmembership_can_view_net_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover'), ('diners_club', 'Diners Club'), ('american_express', 'American Express')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='source',
            field=models.CharField(default='walk-in', max_length=100),
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('phone_no', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_dealers', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='core.cardealer'),
        ),
        migrations.CreateModel(
            name='CustomSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sources', to='core.organization')),
            ],
        ),
    ]
