# Generated by Django 6.0.4 on 2026-05-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servicerecord_payment_method_servicerecord_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='insurance_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='registration_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
