# Generated by Django 6.0.4 on 2026-05-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicerecord_insurance_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='terminal_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='transaction_type',
            field=models.CharField(blank=True, default='OLRS', max_length=80),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
