# Generated by Django 6.0.4 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_servicerecord_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_manage_dealers',
            field=models.BooleanField(default=False, help_text='Can this agent manage dealerships?'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='expected_payment_date',
            field=models.DateField(blank=True, help_text='When is the dealer expected to pay?', null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='is_dealer_paid',
            field=models.BooleanField(default=False, help_text='Has the dealer paid for this service?'),
        ),
    ]
