# Generated by Django 6.0.4 on 2026-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organizationmembership_can_manage_dealers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='dealer_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount owed by the dealer for this service.', max_digits=10),
        ),
    ]
