# Generated by Django 6.0.4 on 2026-05-02 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_servicerecord_dealer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check #, Transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.cardealer')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
