# Generated by Django 6.0.4 on 2026-05-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dealerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedocument',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.servicerecord'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='walk-in', max_length=100)),
                ('is_partner', models.BooleanField(default=False, help_text='Is this dealer a partner?')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('ssn', models.CharField(blank=True, default='', max_length=11)),
                ('driver_license', models.CharField(blank=True, default='', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('building_no', models.CharField(blank=True, default='', max_length=20)),
                ('street_address', models.CharField(blank=True, default='', max_length=200)),
                ('apartment', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NY', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.cardealer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('passenger', 'Passenger Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('trailer', 'Trailer'), ('other', 'Other')], default='passenger', max_length=50)),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('plate_number', models.CharField(blank=True, default='', max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('body_type', models.CharField(blank=True, choices=[('2door', '2-Doors'), ('4door', '4-Doors'), ('truck', 'Truck'), ('van', 'Van'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('suv', 'SUV'), ('other', 'Other')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('fuel_type', models.CharField(choices=[('gas', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('natural_gas', 'Natural Gas'), ('other', 'Other')], default='gas', max_length=50)),
                ('cylinders', models.CharField(blank=True, default='', max_length=20)),
                ('seats', models.CharField(blank=True, default='', max_length=20)),
                ('registration_effective_date', models.DateField(blank=True, null=True)),
                ('registration_expiration_date', models.DateField(blank=True, null=True)),
                ('insurance_expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='core.vehicle'),
        ),
    ]
