# Generated by Django 6.0.4 on 2026-05-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_servicedocument_service_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
