# Generated by Django 6.0.4 on 2026-05-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cardealer_is_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='dl_number',
            field=models.CharField(blank=True, default='', help_text='Driver license number for this vehicle/owner', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', help_text='Internal vehicle number', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_agents',
            field=models.IntegerField(default=5, help_text='Maximum number of agents allowed for this Agency.'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can this agent view Agency reports?'),
        ),
    ]
