# Generated by Django 6.0.4 on 2026-05-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vehicle_dl_number_vehicle_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'PSB', 'verbose_name_plural': 'PSBs'},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['organization__name', 'user__username'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='case_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='reminders_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Agent')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder_45', '45-Day Reminder'), ('reminder_30', '30-Day Reminder'), ('reminder_15', '15-Day Reminder'), ('final_warning', 'Final Warning'), ('expired_warning', 'Expired Warning')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('details', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='core.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='core.organization')),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='core.servicerecord')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
