# Generated by Django 6.0.4 on 2026-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='case_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
