# Generated by Django 6.0.4 on 2026-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_servicerecord_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
