# Generated by Django 6.0.4 on 2026-05-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_organizationmembership_can_trigger_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerpayment',
            name='payment_type',
            field=models.CharField(choices=[('debt', 'Initial Debt'), ('payment', 'Dealer Payment'), ('adjustment', 'Balance Adjustment')], default='payment', max_length=20),
        ),
        migrations.AddField(
            model_name='dealerpayment',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_payments', to='core.servicerecord'),
        ),
        migrations.AlterField(
            model_name='automationlog',
            name='log_type',
            field=models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder_45', '45-Day Reminder'), ('reminder_30', '30-Day Reminder'), ('reminder_15', '15-Day Reminder'), ('final_warning', 'Final Warning'), ('expired_warning', 'Expired Warning'), ('completed', 'Process Completed')], max_length=30),
        ),
    ]
