# Generated by Django 6.0.4 on 2026-05-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cardealer_deleted_at_client_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='insurance_company',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='insurance_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='insurance_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_company',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_type',
            field=models.CharField(choices=[('personal', 'Personal Plates'), ('commercial', 'Commercial Plates')], default='personal', max_length=20),
        ),
    ]
