# Generated by Django 6.0.4 on 2026-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_servicerecord_insurance_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable Automation Hub features for this Agency.'),
        ),
    ]
