# Generated by Django 6.0.4 on 2026-05-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_organization_is_automation_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='insurance_effective_date',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='insurance_expiration_date',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='registration_expiration_date',
        ),
    ]
