# Generated by Django 6.0.4 on 2026-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_servicerecord_insurance_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='can_trigger_automation',
        ),
    ]
