# Generated by Django 6.0.4 on 2026-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_can_trigger_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_trigger_automation',
            field=models.BooleanField(default=False, help_text='Can this user manually trigger the automation scan?'),
        ),
    ]
