# Generated by Django 6.0.4 on 2026-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_clientnote_assigned_to'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='core_client_organiz_5e58ad_idx',
            old_name='core_client_organiz_6b5bc4_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='core_client_organiz_a93541_idx',
            old_name='core_client_organiz_57b6a8_idx',
        ),
        migrations.RenameIndex(
            model_name='clientnote',
            new_name='core_client_client__75ed4c_idx',
            old_name='core_clientn_client__1b3c6c_idx',
        ),
        migrations.RenameIndex(
            model_name='clientnote',
            new_name='core_client_follow__68ea60_idx',
            old_name='core_clientn_follow_u_3da41a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_user_id_f286cd_idx',
            old_name='core_notifi_user_is_0b4bf2_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceauditlog',
            new_name='core_servic_organiz_d21c63_idx',
            old_name='core_servicea_organiz_7afc77_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceauditlog',
            new_name='core_servic_service_844092_idx',
            old_name='core_servicea_service_3f8ae2_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerecord',
            new_name='core_servic_organiz_7221f5_idx',
            old_name='core_servic_organiza_d0f87f_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerecord',
            new_name='core_servic_organiz_5a8c3f_idx',
            old_name='core_servic_organiza_417c34_idx',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
