# Generated by Django 6.0.4 on 2026-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_core_client_organiz_6b5bc4_idx_core_client_organiz_5e58ad_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Agency contact number for clients.', max_length=20),
        ),
    ]
