# Generated by Django 6.0.4 on 2026-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_organization_slug_organization_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site News',
                'verbose_name_plural': 'Site News',
                'ordering': ['-created_at'],
            },
        ),
    ]
