# Generated by Django 6.0.4 on 2026-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_sitenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid by the client/dealer at the time of service.', max_digits=10),
        ),
    ]
