# Generated by Django 6.0.4 on 2026-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_servicerecord_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='client_identifier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='driver_license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
