# Generated by Django 6.0.4 on 2026-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_servicerecord_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional extra fees.', max_digits=10),
        ),
    ]
