# Generated by Django 6.0.4 on 2026-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_servicerecord_other_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='transaction_type',
            field=models.CharField(choices=[('OLRS', 'OLRS'), ('transmittal', 'Transmittal')], default='OLRS', max_length=80),
        ),
    ]
