# Generated by Django 6.0.4 on 2026-05-12 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_servicerecord_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='dealerpayment',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='dealerpayment',
            name='service_record',
        ),
        migrations.RenameField(
            model_name='organizationmembership',
            old_name='can_manage_dealers',
            new_name='can_manage_referrals',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='is_dealer_paid',
            new_name='is_referral_paid',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='dealer_balance',
            new_name='referral_balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_partner',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('dealer', 'Car Dealer'), ('travel', 'Travel Agency'), ('broker', 'Broker'), ('customer', 'Customer'), ('custom', 'Custom')], default='dealer', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('phone_no', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_partner', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.referral'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='core.referral'),
        ),
        migrations.CreateModel(
            name='ReferralPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('debt', 'Initial Debt'), ('payment', 'Referral Payment'), ('adjustment', 'Balance Adjustment')], default='payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check #, Transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.referral')),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_payments', to='core.servicerecord')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CarDealer',
        ),
        migrations.DeleteModel(
            name='DealerPayment',
        ),
    ]
