# Generated by Django 6.0.4 on 2026-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_client_dealer_remove_dealerpayment_dealer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='can_manage_referrals',
            field=models.BooleanField(default=False, help_text='Can this agent manage referral partners?'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='expected_payment_date',
            field=models.DateField(blank=True, help_text='When is the referral expected to pay?', null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='is_referral_paid',
            field=models.BooleanField(default=False, help_text='Has the referral paid for this service?'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid by the client/referral at the time of service.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount owed by the referral for this service.', max_digits=10),
        ),
    ]
