# Generated by Django 6.0.4 on 2026-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_organizationmembership_can_manage_referrals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='category',
            field=models.CharField(choices=[('referral', 'Car Referral'), ('travel', 'Travel Agency'), ('broker', 'Broker'), ('customer', 'Customer'), ('custom', 'Custom')], default='referral', max_length=50),
        ),
    ]
