# Generated by Django 6.0.4 on 2026-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_referral_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='category',
            field=models.CharField(choices=[('dealer', 'Car Dealer'), ('travel', 'Travel Agency'), ('broker', 'Broker'), ('customer', 'Customer'), ('custom', 'Custom')], default='dealer', max_length=50),
        ),
    ]
