# Generated by Django 6.0.4 on 2026-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_referral_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
