# Generated by Django 6.0.4 on 2026-05-12 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_referral_initial_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_license', models.CharField(max_length=50)),
                ('ssn_last_4', models.CharField(blank=True, default='', max_length=4)),
                ('building_no', models.CharField(blank=True, default='', max_length=20)),
                ('street_address', models.CharField(max_length=200)),
                ('apartment', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='NY', max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(blank=True, default='', max_length=100)),
                ('vin', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_type', models.CharField(default='passenger', max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(default='gas', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('cylinders', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_type', models.CharField(default='Registration and Title', max_length=100)),
                ('insurance_company', models.CharField(blank=True, default='', max_length=150)),
                ('insurance_policy_number', models.CharField(blank=True, default='', max_length=100)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='core.organization')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Intake',
                'verbose_name_plural': 'Client Intakes',
                'ordering': ['-created_at'],
            },
        ),
    ]
