# Generated by Django 6.0.4 on 2026-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_clientintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='dtf802_file',
            field=models.FileField(blank=True, null=True, upload_to='intake_docs/dtf802/'),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='dtf803_file',
            field=models.FileField(blank=True, null=True, upload_to='intake_docs/dtf803/'),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='mv82_file',
            field=models.FileField(blank=True, null=True, upload_to='intake_docs/mv82/'),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='other_docs',
            field=models.FileField(blank=True, null=True, upload_to='intake_docs/other/'),
        ),
    ]
