# Generated by Django 6.0.4 on 2026-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_clientintake_dtf802_file_clientintake_dtf803_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='insurance_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='insurance_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
