# Generated by Django 6.0.4 on 2026-05-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_clientintake_insurance_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='driver_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='state',
            field=models.CharField(blank=True, default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
