# Generated by Django 6.0.4 on 2026-05-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_clientintake_city_alter_clientintake_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='requested_services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
