# Generated by Django 6.0.4 on 2026-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_clientintake_requested_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='portal_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
