# Generated by Django 6.0.4 on 2026-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_organization_portal_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='co_registrant_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='co_registrant_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='co_registrant_nys_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='has_lien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='is_bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='is_leased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='is_registrant_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='lessor_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='lessor_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='lien_filing_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='lienholder_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='lienholder_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='max_gross_weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='mv82_transaction_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='num_axles',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='odometer_reading',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='odometer_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='owner_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='owner_nys_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='plate_to_transfer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_address_same',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_apartment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_building_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_state',
            field=models.CharField(blank=True, default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_street_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='residence_zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='seating_capacity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
