# Generated by Django 6.0.4 on 2026-05-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_clientintake_co_registrant_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='max_gross_weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='num_axles',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_reading',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
