# Generated by Django 6.0.4 on 2026-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_vehicle_co_registrant_dob_vehicle_co_registrant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='residence_apartment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='residence_building_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='residence_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='residence_county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='residence_street_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='residence_zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
