# Generated by Django 6.0.4 on 2026-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_client_residence_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mv82_file',
            field=models.FileField(blank=True, null=True, upload_to='client_docs/mv82/'),
        ),
    ]
