# Generated by Django 6.0.5 on 2026-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_client_mv82_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='driver_license',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='driver_license',
            field=models.CharField(default='', max_length=50),
        ),
    ]
