# Generated by Django 6.0.5 on 2026-05-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_client_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='driver_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientintake',
            name='driver_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
