# Generated by Django 6.0.5 on 2026-05-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_inventoryservice_marketingcampaignlog'),
        ('core', '0063_alter_client_driver_license_and_more'),
    ]

    operations = [
    ]
