# Generated by Django 6.0.5 on 2026-05-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_20260530_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('zelle', 'Zelle'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover'), ('diners_club', 'Diners Club'), ('american_express', 'American Express')], default='cash', max_length=50),
        ),
    ]
