# Generated by Django 6.0.4 on 2026-06-01 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date printed on the receipt'),
        ),
    ]
