# Generated by Django 6.0.4 on 2026-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_servicerecord_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='dmv_sales_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales tax portion for the DMV.', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='other_dmv_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional extra fees for DMV.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional extra fees for PSB.', max_digits=10),
        ),
    ]
