# Generated by Django 6.0.4 on 2026-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_servicerecord_dmv_sales_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='review_link',
            field=models.URLField(blank=True, help_text='The URL that the review button will link to.', max_length=500, null=True, verbose_name='Review/Custom Link'),
        ),
        migrations.AddField(
            model_name='organization',
            name='show_review_button',
            field=models.BooleanField(default=False, help_text='Add a custom review button to the intake completion page.', verbose_name='Show Review Button on Success Page'),
        ),
    ]
