# Generated by Django 6.0.4 on 2026-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_organization_insurance_space_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('2door', '2-Doors'), ('4door', '4-Doors'), ('truck', 'Truck'), ('van', 'Van'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('suv', 'SUV'), ('motorcycle', 'Motorcycle'), ('van_truck', 'Van Truck'), ('flat_bed_truck', 'Flat bed truck'), ('tank_truck', 'Tank Truck'), ('tow', 'Tow'), ('limo', 'Limo'), ('light_trailer', 'Light Trailer'), ('wagon', 'Wagon'), ('tractor', 'Tractor'), ('na', 'N/A'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_type',
            field=models.CharField(choices=[('personal', 'Personal Plates'), ('commercial', 'Commercial Plates'), ('motorcycle', 'Motorcycle plates'), ('atv', 'ATV plates'), ('trailer', 'Trailer Plates')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('passenger', 'Passenger Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('trailer', 'Trailer'), ('moped', 'Moped'), ('boat', 'Boat'), ('jetski', 'Jetski'), ('mobile_home', 'Mobile Home'), ('snowmobile', 'Snowmobile'), ('atv', 'ATV'), ('dump', 'Dump'), ('other', 'Other')], default='passenger', max_length=50),
        ),
    ]
