# Generated by Django 6.0.4 on 2026-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_vehicle_vin_vehicle_unique_active_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='signature',
            field=models.ImageField(blank=True, help_text='Agent signature image to be displayed on receipts.', null=True, upload_to='agent_signatures/'),
        ),
    ]
