# Generated by Django 6.0.4 on 2026-06-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_organizationmembership_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcampaignlog',
            name='inventory_service',
        ),
        migrations.RemoveField(
            model_name='marketingcampaignlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='marketingcampaignlog',
            name='sent_by',
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='core.organization')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('organization', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='InventoryService',
        ),
        migrations.DeleteModel(
            name='MarketingCampaignLog',
        ),
    ]
