# Generated by Django 6.0.4 on 2026-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_marketingcampaignlog_inventory_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='accessible_spaces',
            field=models.ManyToManyField(blank=True, help_text='Specific spaces this agent has access to.', related_name='permitted_memberships', to='core.space'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='can_view_spaces',
            field=models.BooleanField(default=False, help_text='Can this agent view the main Spaces page?'),
        ),
    ]
