# Generated by Django 6.0.4 on 2026-06-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_organizationmembership_accessible_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Agent who added this policy/quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_insurance_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='broker_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Broker fee taken by the agent', max_digits=12),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='can_deal_with_insurance',
            field=models.BooleanField(default=False, help_text='Can this agent deal with insurance and appear in the insurance workspace?'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(choices=[('quote', 'Quote'), ('bound', 'Bound'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
