# Generated by Django 6.0.4 on 2026-06-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_insurancepolicy_added_by_insurancepolicy_broker_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.insurancecompany'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='stage',
            field=models.CharField(choices=[('quote', 'Quote'), ('bound', 'Bound')], default='quote', max_length=20),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
