# Generated by Django 6.0.4 on 2026-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_vehicle_vin_unique_per_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_ein',
            field=models.CharField(blank=True, default='', help_text='Employer Identification Number (EIN) for commercial accounts', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, default='', help_text='Business or company name (for commercial accounts)', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='is_commercial',
            field=models.BooleanField(default=False, help_text='Check if this is a commercial/business account'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('auto_personal', 'AUTO PERSONAL'), ('motor_cycle', 'MOTOR CYCLE'), ('commercial_auto', 'COMMERCIAL AUTO'), ('trucking', 'TRUCKING'), ('contractors', 'CONTRACTORS'), ('landscaping', 'LANDSCAPING'), ('dealer_plates', 'DEALER PLATES'), ('home_owners', 'HOME OWNERS'), ('ho3', 'HO3'), ('ho4', 'HO4'), ('ho6', 'HO6'), ('dwelling', 'DWELLING'), ('umbrella', 'UMBRELLA'), ('business_owners_policy', 'BUSINESS OWNERS POLICY'), ('general_liability', 'GENERAL LIABILITY'), ('workers_compensation', 'WORKERS COMPENSATION'), ('disability', 'DISABILITY')], default='', help_text='Type of insurance policy', max_length=30),
        ),
    ]
