# Generated by Django 6.0.4 on 2026-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_insurance_type_and_commercial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='business_ein',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientintake',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
    ]
