# Generated by Django 6.0.4 on 2026-06-04 13:51

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_add_commercial_fields_to_clientintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='InsuranceCompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('document', models.FileField(upload_to=core.models.insurance_company_document_upload_path)),
                ('document_date', models.DateField(blank=True, help_text='Date associated with this document', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.insurancecompany')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
