# Generated by Django 6.0.4 on 2026-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_insurancepolicy_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='paid_amount_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='payment_method_2',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('zelle', 'Zelle'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover'), ('diners_club', 'Diners Club'), ('american_express', 'American Express')], max_length=50, null=True),
        ),
    ]
