# Generated by Django 6.0.4 on 2026-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_servicerecord_paid_amount_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='bound_date',
            field=models.DateField(blank=True, help_text='Date the policy was bound', null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='business_type',
            field=models.CharField(choices=[('new_business', 'New Business'), ('renewal', 'Renewal'), ('rewrite', 'Rewrite')], default='new_business', max_length=50),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-In'), ('google_search', 'Google Search'), ('meta_platform', 'Meta Platform'), ('google_campaigns', 'Google Campaigns'), ('existing_client', 'Existing Client'), ('dealer', 'Dealer'), ('referral', 'Referral'), ('cold_calling', 'Cold Calling')], default='walk_in', max_length=50),
        ),
    ]
