# Generated by Django 6.0.4 on 2026-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_insurancepolicy_bound_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_delete_receipt',
            field=models.BooleanField(default=False, help_text='Can this agent delete/remove receipt records from the service list?'),
        ),
    ]
