# Generated by Django 6.0.4 on 2026-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_can_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_view_banking',
            field=models.BooleanField(default=False, help_text='Can this agent view the banking section in the insurance space?'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='can_view_commission',
            field=models.BooleanField(default=False, help_text='Can this agent view commission rate, commission amount, and agency profit in the insurance space?'),
        ),
    ]
