# Generated by Django 6.0.4 on 2026-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_commission_banking_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_manage_news',
            field=models.BooleanField(default=False, help_text='Can this agent add, edit, or delete news/announcements?'),
        ),
    ]
