# Generated by Django 6.0.4 on 2026-06-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_organizationmembership_can_manage_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHubMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, help_text='Upload training PDF, document, or media file', null=True, upload_to='knowledge_hub/')),
                ('external_url', models.URLField(blank=True, default='', help_text='Optional link to external video, course, or doc')),
                ('step_number', models.PositiveIntegerField(default=1, help_text='Roadmap step order (1, 2, 3...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.space')),
            ],
            options={
                'verbose_name': 'Knowledge Hub Material',
                'verbose_name_plural': 'Knowledge Hub Materials',
                'ordering': ['step_number', 'created_at'],
            },
        ),
    ]
