# Generated by Django 6.0.4 on 2026-06-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_knowledgehubmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubmaterial',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent roadmap step for nesting sub-steps', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_materials', to='core.knowledgehubmaterial'),
        ),
        migrations.AddField(
            model_name='knowledgehubmaterial',
            name='roadmap_name',
            field=models.CharField(default='General Roadmap', help_text='Name of the training roadmap this step belongs to', max_length=100),
        ),
    ]
