# Generated by Django 6.0.4 on 2026-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_knowledgehubmaterial_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_manage_knowledge_hub',
            field=models.BooleanField(default=False, help_text='Can this agent add or delete materials in the Knowledge Hub?'),
        ),
    ]
