# Generated by Django 6.0.4 on 2026-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_add_can_manage_knowledge_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintake',
            name='source',
            field=models.CharField(choices=[('google_search', 'Google Search'), ('walk_in', 'Walk-In'), ('meta_platform', 'Meta Platform'), ('google_campaigns', 'Google Campaigns'), ('existing_client', 'Existing Client'), ('dealer', 'Dealer'), ('referral', 'Referral'), ('cold_calling', 'Cold Calling'), ('other', 'Other')], default='google_search', max_length=50),
        ),
    ]
