# Generated by Django 6.0.4 on 2026-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_add_source_to_clientintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedocument',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text="Custom name for 'other' document types", max_length=150),
        ),
    ]
