# Generated by Django 6.0.4 on 2026-06-09 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_inventory_invoice_sales_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_type_options', to='core.organization')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('organization', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ReferralCategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_category_options', to='core.organization')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
