# Generated by Django 6.0.4 on 2026-06-09 17:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_vehicle_is_legacy_vin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_deal_with_motorclub',
            field=models.BooleanField(default=False, help_text='Can this member sell and manage Motor Club roadside memberships?'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='accessible_spaces',
            field=models.ManyToManyField(blank=True, help_text='Specific spaces this member (including PSB owners) can open.', related_name='permitted_memberships', to='core.space'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='can_view_spaces',
            field=models.BooleanField(default=False, help_text='Can this member (including PSB owners) view the main Spaces page?'),
        ),
        migrations.CreateModel(
            name='MotorclubB2BPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorclub_b2b_partners', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MotorclubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_35_provider_take', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Amount the Motor Club provider keeps from the $35 plan.', max_digits=8)),
                ('tier_50_provider_take', models.DecimalField(decimal_places=2, default=Decimal('28.00'), help_text='Amount the Motor Club provider keeps from the $50 plan.', max_digits=8)),
                ('tier_75_provider_take', models.DecimalField(decimal_places=2, default=Decimal('42.00'), help_text='Amount the Motor Club provider keeps from the $75 plan.', max_digits=8)),
                ('tier_100_provider_take', models.DecimalField(decimal_places=2, default=Decimal('55.00'), help_text='Amount the Motor Club provider keeps from the $100 plan.', max_digits=8)),
                ('provider_profit_notes', models.TextField(blank=True, default='', help_text='Notes about Motor Club provider / company profit expectations.')),
                ('psb_profit_notes', models.TextField(blank=True, default='', help_text='Notes about PSB profit goals for Motor Club sales.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorclub_config', to='core.organization')),
            ],
            options={
                'verbose_name': 'Motor Club configuration',
            },
        ),
        migrations.CreateModel(
            name='MotorclubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('insurance_client', 'Insurance Client'), ('b2b', 'B2B Partner'), ('direct', 'Direct / Walk-In')], default='direct', max_length=20)),
                ('tier', models.PositiveSmallIntegerField(choices=[(35, '$35 / year'), (50, '$50 / year'), (75, '$75 / year'), (100, '$100 / year')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('membership_number', models.CharField(blank=True, default='', max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('provider_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Motor Club provider / company profit for this membership.', max_digits=8)),
                ('psb_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PSB profit for this membership.', max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_motorclub_memberships', to=settings.AUTH_USER_MODEL)),
                ('b2b_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.motorclubb2bpartner')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorclub_memberships', to='core.client')),
                ('insurance_policy', models.ForeignKey(blank=True, help_text='Optional link when sold to an existing insurance client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorclub_memberships', to='core.insurancepolicy')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorclub_memberships', to='core.organization')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorclub_memberships', to='core.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
