# Generated by Django 6.0.4 on 2026-06-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_insurancepolicy_commission_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('zelle', 'Zelle'), ('checks', 'Checks'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover'), ('diners_club', 'Diners Club'), ('american_express', 'American Express')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='payment_method_2',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('zelle', 'Zelle'), ('checks', 'Checks'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover'), ('diners_club', 'Diners Club'), ('american_express', 'American Express')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InsuranceAgentRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_pipeline', models.BooleanField(default=True, help_text='Include this agent in the round-robin pipeline.')),
                ('is_present', models.BooleanField(default=True, help_text='When off, agent is treated as absent until turned back on.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_rotation', to='core.organizationmembership')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAgentHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.insuranceagentrotation')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDistributionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Automatically assign new policies to the next agent in the pipeline.')),
                ('only_insurance_agents', models.BooleanField(default=True, help_text="Limit the pipeline to members with 'Can deal with insurance'.")),
                ('allow_manual_override', models.BooleanField(default=True, help_text='Owners can manually pick an agent when adding a policy.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_distribution_config', to='core.organization')),
            ],
            options={
                'verbose_name': 'Insurance distribution configuration',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDistributionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organizationmembership')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_distribution_state', to='core.organization')),
            ],
        ),
    ]
