# Generated by Django 6.0.4 on 2026-06-10 13:40

from django.db import migrations, models


def enable_existing_distribution_configs(apps, schema_editor):
    InsuranceDistributionConfig = apps.get_model("core", "InsuranceDistributionConfig")
    InsuranceDistributionConfig.objects.filter(is_enabled=False).update(is_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_insurance_distribution_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedistributionconfig',
            name='allow_manual_override',
            field=models.BooleanField(default=True, help_text='Staff can manually pick an agent when adding a policy (Django Admin).'),
        ),
        migrations.AlterField(
            model_name='insurancedistributionconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Automatically assign new policies to the next agent in the pipeline.'),
        ),
        migrations.RunPython(enable_existing_distribution_configs, migrations.RunPython.noop),
    ]
