# Generated by Django 6.0.4 on 2026-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_insurance_distribution_enabled_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_manage_insurance_pipeline',
            field=models.BooleanField(default=False, help_text='Can this agent configure the insurance distribution pipeline and assign agents to it?'),
        ),
        migrations.AlterField(
            model_name='insurancedistributionconfig',
            name='allow_manual_override',
            field=models.BooleanField(default=True, help_text='Users with pipeline permission can manually pick an agent when adding a policy.'),
        ),
    ]
