# Generated by Django 6.0.4 on 2026-06-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_membership_can_manage_insurance_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='insurance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_notifications', to='core.insurancepolicy'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], db_index=True, default='warning', max_length=20),
        ),
    ]
