# Generated by Django 6.0.4 on 2026-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_notification_insurance_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceagentrotation',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='insurancedistributionconfig',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='insurancedistributionstate',
            name='last_membership',
        ),
        migrations.RemoveField(
            model_name='insurancedistributionstate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='insurance_policy',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='can_manage_insurance_pipeline',
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning')], db_index=True, default='warning', max_length=20),
        ),
        migrations.DeleteModel(
            name='InsuranceAgentHoliday',
        ),
        migrations.DeleteModel(
            name='InsuranceAgentRotation',
        ),
        migrations.DeleteModel(
            name='InsuranceDistributionConfig',
        ),
        migrations.DeleteModel(
            name='InsuranceDistributionState',
        ),
    ]
