# Generated by Django 6.0.4 on 2026-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_insurance_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='stage',
            field=models.CharField(choices=[('quote', 'Quote'), ('bound', 'Bound'), ('endorsement_quote', 'Endorsement — Quote'), ('endorsement_bound', 'Endorsement — Bound')], default='quote', max_length=20),
        ),
    ]
