# Generated by Django 6.0.4 on 2026-06-08

import decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_organization_psbc_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_manage_documents',
            field=models.BooleanField(
                default=False,
                help_text='Can this agent create folders, document types, and records in the Documents space?',
            ),
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folders_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.documentfolder')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='core.space')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='core.organization')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='core.space')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('space', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SpaceDocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('order_number', models.CharField(blank=True, default='', max_length=80)),
                ('range_start', models.CharField(blank=True, default='', max_length=80)),
                ('range_end', models.CharField(blank=True, default='', max_length=80)),
                ('total_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='space_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_documents_added', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.spacedocumenttype')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.documentfolder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='core.organization')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='core.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('space', 'parent', 'name'), name='unique_document_folder_name_per_parent'),
        ),
    ]
