# Generated by Django 6.0.4 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_documents_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacedocumentrecord',
            old_name='total_amount',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='spacedocumentrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
