# Generated by Django 6.0.4 on 2026-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_clientintake_partner_note_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintake',
            name='source',
            field=models.CharField(choices=[('google_search', 'Google Search'), ('walk_in', 'Walk-In'), ('meta_platform', 'Meta Platform'), ('google_campaigns', 'Google Campaigns'), ('existing_client', 'Existing Client'), ('dealer', 'Dealer / Referral'), ('cold_calling', 'Cold Calling'), ('other', 'Other')], default='google_search', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('2door', '2-Doors'), ('4door', '4-Doors'), ('truck', 'Truck'), ('van', 'Van'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('suv', 'SUV'), ('suburban', 'Suburban'), ('pickup_truck', 'Pick Up Truck'), ('motorcycle', 'Motorcycle'), ('van_truck', 'Van Truck'), ('flat_bed_truck', 'Flat bed truck'), ('tank_truck', 'Tank Truck'), ('tow', 'Tow'), ('limo', 'Limo'), ('light_trailer', 'Light Trailer'), ('wagon', 'Wagon'), ('tractor', 'Tractor'), ('na', 'N/A'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
