# Generated by Django 6.0.5 on 2026-06-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clientintake",
            name="core_intake_org_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="insurancepolicy",
            name="core_ins_org_client_idx",
        ),
        migrations.RemoveIndex(
            model_name="insurancepolicy",
            name="core_ins_org_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicerecord",
            name="core_svc_ref_unpaid_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicerecord",
            name="core_svc_org_unpaid_idx",
        ),
        migrations.RenameIndex(
            model_name="sitenewsread",
            new_name="core_sitene_user_id_e44a2d_idx",
            old_name="core_sitene_user_id_6f0a8b_idx",
        ),
    ]
