# Generated by Django 6.0.5 on 2026-06-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_organization_email"),
        ("core", "0123_remove_clientintake_core_intake_org_status_idx_and_more"),
    ]

    operations = []
