# Generated by Django 5.x

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0151_agent_portal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancepolicy",
            name="renewal_date",
            field=models.DateField(
                blank=True,
                help_text="Renewal / next-term date (usually set from DEC expiration).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InsurancePolicyDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("declaration_page", "Declaration Page"),
                            ("id_cards", "ID Cards"),
                            ("payment_receipt", "Payment Receipt"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(blank=True, null=True, upload_to="insurance_policy_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.insurancepolicy",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_policy_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="InsurancePolicyInstallment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "installment_number",
                    models.PositiveSmallIntegerField(
                        help_text="0 = deposit / down payment; bills start at 1.",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("installment_fee", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("is_paid", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="core.insurancepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "installment_number"],
                "unique_together": {("policy", "installment_number")},
            },
        ),
    ]
