# Generated by Django 6.0.4 on 2026-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0189_organization_client_app_portal_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="source",
            field=models.CharField(
                choices=[
                    ("google_search", "Google Search"),
                    ("walk_in", "Walk-In"),
                    ("website", "Website"),
                    ("meta_platform", "Meta Platform"),
                    ("google_campaigns", "Google Campaigns"),
                    ("existing_client", "Existing Client"),
                    ("lost_client", "Lost Client"),
                    ("dealer", "Dealer"),
                    ("referral", "Referral"),
                    ("cold_calling", "Cold Calling"),
                    ("insurance", "Insurance"),
                    ("other", "Other"),
                    ("walk-in", "Walk-In (legacy)"),
                ],
                default="walk_in",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="clientintake",
            name="source",
            field=models.CharField(
                choices=[
                    ("google_search", "Google Search"),
                    ("walk_in", "Walk-In"),
                    ("website", "Website"),
                    ("meta_platform", "Meta Platform"),
                    ("google_campaigns", "Google Campaigns"),
                    ("existing_client", "Existing Client"),
                    ("lost_client", "Lost Client"),
                    ("dealer", "Dealer / Referral"),
                    ("cold_calling", "Cold Calling"),
                    ("other", "Other"),
                ],
                default="google_search",
                max_length=50,
            ),
        ),
    ]
