# Generated by Django 6.0.4 on 2026-10-05 14:40

import core.insurance_esign_models
import core.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_quote_lead_crm_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['account_name'], 'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Bank transaction', 'verbose_name_plural': 'Bank transactions'},
        ),
        migrations.AlterModelOptions(
            name='dailypaymenttransaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Daily payment', 'verbose_name_plural': 'Daily payments'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['name'], 'verbose_name': 'Insurance company', 'verbose_name_plural': 'Insurance companies'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompanydocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Insurance company document', 'verbose_name_plural': 'Insurance company documents'},
        ),
        migrations.AlterModelOptions(
            name='insuranceesignenvelope',
            options={'ordering': ['-created_at'], 'verbose_name': 'Insurance e-signature envelope', 'verbose_name_plural': 'Insurance e-signature envelopes'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Insurance policy', 'verbose_name_plural': 'Insurance policies'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicydocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Insurance policy document', 'verbose_name_plural': 'Insurance policy documents'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicyinstallment',
            options={'ordering': ['due_date', 'installment_number'], 'verbose_name': 'Insurance policy installment', 'verbose_name_plural': 'Insurance policy installments'},
        ),
        migrations.AlterModelOptions(
            name='insurancetypeoption',
            options={'ordering': ['label'], 'verbose_name': 'Insurance type option', 'verbose_name_plural': 'Insurance type options'},
        ),
        migrations.AlterModelOptions(
            name='tlccarrier',
            options={'ordering': ['name'], 'verbose_name': 'TLC carrier', 'verbose_name_plural': 'TLC carriers'},
        ),
        migrations.AlterModelOptions(
            name='tlcendorsement',
            options={'ordering': ['-coverage_change_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tlcfinancecompany',
            options={'ordering': ['name'], 'verbose_name': 'TLC finance company', 'verbose_name_plural': 'TLC finance companies'},
        ),
        migrations.AlterModelOptions(
            name='tlcpaymenttransaction',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'TLC payment', 'verbose_name_plural': 'TLC payments'},
        ),
        migrations.AlterModelOptions(
            name='tlcreceipt',
            options={'ordering': ['-generated_at', '-id'], 'verbose_name': 'TLC receipt', 'verbose_name_plural': 'TLC receipts'},
        ),
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='core_banktx_acct_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='insurancepolicy',
            name='core_inspol_org_stage_bound_idx',
        ),
        migrations.RemoveIndex(
            model_name='insurancepolicy',
            name='core_inspol_org_stage_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='insurancepolicy',
            name='core_inspol_org_co_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerecord',
            name='core_svcrec_org_txdate_idx',
        ),
        migrations.RenameIndex(
            model_name='agentactivityevent',
            new_name='core_agenta_organiz_5fb9b9_idx',
            old_name='core_agenta_organiz_7f2c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='clientchatmessage',
            new_name='core_client_client__a64a2b_idx',
            old_name='core_client_client__7a2e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='clientchatmessage',
            new_name='core_client_client__342fb4_idx',
            old_name='core_client_client__b8c1d2_idx',
        ),
        migrations.RenameIndex(
            model_name='insurancequotelead',
            new_name='core_insura_organiz_8fb9a6_idx',
            old_name='core_insura_organiz_quote_stg_idx',
        ),
        migrations.RenameIndex(
            model_name='insurancequotelead',
            new_name='core_insura_organiz_f0d2e2_idx',
            old_name='core_insura_organiz_quote_asg_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_halloween_theme_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle to enable spooky Halloween theme, spider descent, character icons, and scary logo system-wide.', verbose_name='Enable Halloween Theme & Animations'),
        ),
        migrations.AlterField(
            model_name='agentattendancesession',
            name='work_date',
            field=models.DateField(db_index=True, help_text='America/New_York calendar date this shift belongs to.'),
        ),
        migrations.AlterField(
            model_name='dailypaymenttransaction',
            name='broker_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional service-other-than-insurance amount; shown on the receipt only when greater than zero.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailypaymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('zelle', 'Zelle'), ('credit_card', "Client's Credit Card"), ('checks', 'Checks'), ('payment_hub', 'Payment Hub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='insurancepolicydocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.insurance_policy_document_upload_to),
        ),
        migrations.AlterField(
            model_name='insurancesavedsignature',
            name='image',
            field=models.ImageField(upload_to=core.insurance_esign_models._saved_signature_upload_to),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_owner_name',
            field=models.CharField(blank=True, default='', help_text='Full legal name of the business owner printed on service receipts. Only this field is used — not users with the Owner role.', max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='can_view_banking',
            field=models.BooleanField(default=False, help_text='Can this agent access Banking & Companies in the insurance space, manage commission fields, edit any insurance policy, and mark daily bank payments as cleared?'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='can_view_commission',
            field=models.BooleanField(default=False, help_text='Deprecated: use can_view_banking for commission and finance access.'),
        ),
        migrations.AlterField(
            model_name='tlcendorsement',
            name='endorsement_type',
            field=models.CharField(choices=[('added_driver', 'Added Driver'), ('removed_driver', 'Removed Driver'), ('address_change', 'Address Change'), ('add_vehicle', 'Add a Vehicle'), ('remove_vehicle', 'Remove a Vehicle'), ('replace_vehicle', 'Replace a Vehicle'), ('ddc', 'DDC'), ('coverage_change', 'Coverage Change'), ('plate_change', 'Plate Change'), ('tlc_number_change', 'TLC Number Change'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='tlcinstallment',
            name='installment_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-installment carrier/installment fee deducted from the gross payment.', max_digits=12),
        ),
    ]
