"""Professional PDF layouts for Custom Inventory invoices and reports."""

from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

PAGE_W, PAGE_H = letter
MARGIN = 0.6 * inch
CONTENT_W = PAGE_W - (MARGIN * 2)
LINE_H = 12
CARD_PAD = 14
HEADER_H = 1.2 * inch
FOOTER_H = 0.7 * inch

TEAL = colors.HexColor("#0f766e")
TEAL_DARK = colors.HexColor("#134e4a")
TEAL_LIGHT = colors.HexColor("#f0fdfa")
SLATE = colors.HexColor("#334155")
SLATE_MUTED = colors.HexColor("#64748b")
SLATE_LIGHT = colors.HexColor("#f8fafc")
BORDER = colors.HexColor("#e2e8f0")
WHITE = colors.white


def _wrap_text(text, max_chars=48):
    words = (text or "").split()
    lines, current = [], ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) <= max_chars:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines or [""]


def _card_height(line_count, extra=0):
    return CARD_PAD + 18 + (line_count * LINE_H) + extra


def _draw_page_background(pdf):
    pdf.setFillColor(SLATE_LIGHT)
    pdf.rect(0, FOOTER_H, PAGE_W, PAGE_H - HEADER_H - FOOTER_H, fill=1, stroke=0)


def _draw_header_band(pdf, space, doc_title="INVOICE"):
    pdf.setFillColor(TEAL_DARK)
    pdf.rect(0, PAGE_H - HEADER_H, PAGE_W, HEADER_H, fill=1, stroke=0)
    pdf.setFillColor(TEAL)
    pdf.rect(0, PAGE_H - HEADER_H, PAGE_W, 4, fill=1, stroke=0)

    pdf.setFillColor(WHITE)
    pdf.setFont("Helvetica-Bold", 19)
    pdf.drawString(MARGIN, PAGE_H - 0.48 * inch, (space.label or "Inventory")[:42])

    pdf.setFont("Helvetica", 8.5)
    y_contact = PAGE_H - 0.66 * inch
    contact_lines = []
    if space.business_phone:
        contact_lines.append(space.business_phone)
    if space.business_email:
        contact_lines.append(space.business_email)
    for line in contact_lines:
        pdf.drawString(MARGIN, y_contact, line)
        y_contact -= 10

    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.46 * inch, doc_title)
    pdf.setFont("Helvetica", 8)
    pdf.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.64 * inch, "Official Document")


def _draw_footer(pdf, space, label="Thank you for your business"):
    pdf.setFillColor(TEAL_DARK)
    pdf.rect(0, 0, PAGE_W, FOOTER_H, fill=1, stroke=0)
    pdf.setFillColor(WHITE)
    pdf.setFont("Helvetica", 8)
    pdf.drawCentredString(PAGE_W / 2, 0.38 * inch, f"{label} — {space.label}")
    pdf.setFont("Helvetica-Oblique", 7)
    pdf.drawCentredString(PAGE_W / 2, 0.2 * inch, "This document was generated by your inventory system.")


def _draw_card(pdf, x, top_y, width, title, body_lines, title_color=TEAL):
    h = _card_height(len(body_lines))
    pdf.setStrokeColor(BORDER)
    pdf.setFillColor(WHITE)
    pdf.roundRect(x, top_y - h, width, h, 8, fill=1, stroke=1)
    pdf.setFillColor(colors.HexColor("#ecfdf5"))
    pdf.roundRect(x, top_y - 22, width, 22, 8, fill=1, stroke=0)
    pdf.rect(x, top_y - 22, width, 8, fill=1, stroke=0)
    pdf.setFillColor(title_color)
    pdf.setFont("Helvetica-Bold", 8)
    pdf.drawString(x + CARD_PAD, top_y - 15, title.upper())
    pdf.setFillColor(SLATE)
    pdf.setFont("Helvetica", 9)
    by = top_y - 34
    for i, line in enumerate(body_lines):
        if i == 0 and line.startswith("**"):
            pdf.setFont("Helvetica-Bold", 10)
            pdf.drawString(x + CARD_PAD, by, line.replace("**", "")[:55])
            pdf.setFont("Helvetica", 9)
        else:
            pdf.drawString(x + CARD_PAD, by, line[:60])
        by -= LINE_H
    return h


def _invoice_detail_lines(invoice):
    lines = [
        f"Invoice #: {invoice.invoice_number}",
        f"Date: {invoice.invoice_date.strftime('%B %d, %Y')}",
        f"Payment: {invoice.get_payment_method_display()}",
        f"Status: {invoice.get_status_display()}",
    ]
    if invoice.created_by:
        name = invoice.created_by.get_full_name() or invoice.created_by.username
        lines.append(f"Prepared by: {name}")
    return lines


def _bill_to_lines(invoice):
    lines = [f"**{invoice.buyer_name}"]
    if invoice.buyer_address:
        lines.extend(line.strip() for line in invoice.buyer_address.splitlines() if line.strip())
    if invoice.buyer_phone:
        lines.append(f"Phone: {invoice.buyer_phone}")
    if invoice.buyer_email:
        lines.append(invoice.buyer_email)
    return lines


def _business_address_lines(space):
    if space.business_address:
        return [line.strip() for line in space.business_address.splitlines() if line.strip()]
    return ["Configure address in Business Settings"]


def _ensure_space(pdf, space, min_y, doc_title="INVOICE"):
    if min_y < FOOTER_H + 1.2 * inch:
        _draw_footer(pdf, space)
        pdf.showPage()
        _draw_header_band(pdf, space, doc_title)
        _draw_page_background(pdf)
        return PAGE_H - HEADER_H - 0.35 * inch
    return min_y


def render_inventory_invoice_pdf(pdf, invoice):
    space = invoice.space
    _draw_header_band(pdf, space, "INVOICE")
    _draw_page_background(pdf)

    y = PAGE_H - HEADER_H - 0.35 * inch
    gap = 14
    half_w = (CONTENT_W - gap) / 2

    inv_lines = _invoice_detail_lines(invoice)
    bill_lines = _bill_to_lines(invoice)
    addr_lines = _business_address_lines(space)

    h1 = _card_height(len(inv_lines))
    h2 = _card_height(len(bill_lines))
    row_h = max(h1, h2)

    _draw_card(pdf, MARGIN, y, half_w, "Invoice Details", inv_lines)
    _draw_card(pdf, MARGIN + half_w + gap, y, half_w, "Bill To", bill_lines)
    y -= row_h + gap

    addr_h = _card_height(len(addr_lines))
    _draw_card(pdf, MARGIN, y, CONTENT_W, "From / Business Address", addr_lines)
    y -= addr_h + gap

    # Line items
    y = _ensure_space(pdf, space, y - 30)
    pdf.setFillColor(TEAL)
    pdf.roundRect(MARGIN, y - 24, CONTENT_W, 24, 6, fill=1, stroke=0)
    pdf.setFillColor(WHITE)
    pdf.setFont("Helvetica-Bold", 8)
    pdf.drawString(MARGIN + 10, y - 16, "DESCRIPTION")
    pdf.drawString(MARGIN + CONTENT_W * 0.55, y - 16, "QTY")
    pdf.drawString(MARGIN + CONTENT_W * 0.67, y - 16, "UNIT")
    pdf.drawRightString(PAGE_W - MARGIN - 10, y - 16, "TOTAL")
    y -= 30

    row_idx = 0
    for line in invoice.lines.all():
        desc_lines = _wrap_text(line.description, 42)
        row_h = max(20, 8 + len(desc_lines) * LINE_H)
        y = _ensure_space(pdf, space, y - row_h)
        if row_idx % 2 == 0:
            pdf.setFillColor(TEAL_LIGHT)
            pdf.roundRect(MARGIN, y - row_h + 6, CONTENT_W, row_h, 4, fill=1, stroke=0)
        pdf.setFillColor(SLATE)
        pdf.setFont("Helvetica", 9)
        dy = y - 4
        for dl in desc_lines:
            pdf.drawString(MARGIN + 10, dy, dl)
            dy -= LINE_H
        pdf.drawString(MARGIN + CONTENT_W * 0.55, y - 4, str(line.quantity))
        pdf.drawString(MARGIN + CONTENT_W * 0.67, y - 4, f"${line.unit_price:,.2f}")
        pdf.drawRightString(PAGE_W - MARGIN - 10, y - 4, f"${line.line_total:,.2f}")
        y -= row_h + 4
        row_idx += 1

    y = _ensure_space(pdf, space, y - 80)
    notes_lines = _wrap_text(invoice.notes, 75) if invoice.notes else []
    totals_lines = [
        f"Subtotal: ${invoice.subtotal:,.2f}",
        f"**TOTAL DUE: ${invoice.total:,.2f}",
    ]

    if notes_lines:
        notes_h = _card_height(len(notes_lines))
        _draw_card(pdf, MARGIN, y, CONTENT_W * 0.58, "Notes", notes_lines, title_color=SLATE_MUTED)
        totals_h = _card_height(len(totals_lines))
        _draw_card(
            pdf,
            MARGIN + CONTENT_W * 0.62,
            y,
            CONTENT_W * 0.38,
            "Amount Due",
            totals_lines,
        )
        y -= max(notes_h, totals_h) + gap
    else:
        totals_h = _card_height(len(totals_lines))
        _draw_card(pdf, PAGE_W - MARGIN - CONTENT_W * 0.42, y, CONTENT_W * 0.42, "Amount Due", totals_lines)
        y -= totals_h + gap

    _draw_footer(pdf, space)


def render_inventory_report_pdf(pdf, space, report_type, stats):
    title = "INVENTORY STOCK REPORT" if report_type == "inventory" else "SALES REPORT"
    _draw_header_band(pdf, space, "REPORT")
    _draw_page_background(pdf)

    y = PAGE_H - HEADER_H - 0.35 * inch
    from django.utils import timezone

    meta_lines = [
        f"**{title}",
        f"Business: {space.label}",
        f"Generated: {timezone.localdate().strftime('%B %d, %Y')}",
    ]
    h = _card_height(len(meta_lines))
    _draw_card(pdf, MARGIN, y, CONTENT_W, "Report Overview", meta_lines)
    y -= h + 14

    addr_h = _card_height(len(_business_address_lines(space)))
    _draw_card(pdf, MARGIN, y, CONTENT_W, "Business Address", _business_address_lines(space))
    y -= addr_h + 14

    if report_type == "inventory":
        summary = [
            ("Total Products", str(stats["total_products"])),
            ("Units in Stock", str(stats["total_units"])),
            ("Retail Value", f"${stats['total_inventory_value']:,.2f}"),
            ("Low Stock Items", str(stats["low_stock_count"])),
        ]
    else:
        summary = [
            ("Sales Today", f"${stats['sales_today_total']:,.2f}"),
            ("Sales This Month", f"${stats['sales_month_total']:,.2f}"),
            ("Completed Invoices", str(stats["invoice_count"])),
        ]

    summary_lines = [f"{k}: {v}" for k, v in summary]
    sh = _card_height(len(summary_lines))
    _draw_card(pdf, MARGIN, y, CONTENT_W * 0.5, "Summary", summary_lines)
    y -= sh + 14

    if report_type == "inventory":
        from .inventory_suppliers import enrich_product_profit
        from .models import InventoryProduct

        headers = ["Product", "Cost", "Price", "Margin", "Qty", "Value"]
        rows = []
        for p in InventoryProduct.objects.filter(space=space).select_related("category").order_by("name"):
            enrich_product_profit(p)
            rows.append([
                p.name[:24],
                f"${p.cost_price:,.2f}",
                f"${p.unit_price:,.2f}",
                f"${p.unit_profit:,.2f}",
                str(p.quantity),
                f"${p.unit_price * p.quantity:,.2f}",
            ])
    else:
        from .models import InventoryInvoice

        headers = ["Invoice #", "Date", "Buyer", "Payment", "Total"]
        rows = []
        for inv in InventoryInvoice.objects.filter(space=space).order_by("-invoice_date")[:80]:
            rows.append([
                inv.invoice_number,
                inv.invoice_date.strftime("%m/%d/%Y"),
                inv.buyer_name[:20],
                inv.get_payment_method_display()[:10],
                f"${inv.total:,.2f}",
            ])

    col_count = len(headers)
    col_w = CONTENT_W / col_count
    y = _ensure_space(pdf, space, y - 30, "REPORT")
    pdf.setFillColor(TEAL)
    pdf.roundRect(MARGIN, y - 22, CONTENT_W, 22, 6, fill=1, stroke=0)
    pdf.setFillColor(WHITE)
    pdf.setFont("Helvetica-Bold", 8)
    for i, hname in enumerate(headers):
        x = MARGIN + i * col_w + 6
        if i == col_count - 1:
            pdf.drawRightString(MARGIN + (i + 1) * col_w - 6, y - 14, hname)
        else:
            pdf.drawString(x, y - 14, hname)
    y -= 28

    for ridx, row in enumerate(rows):
        y = _ensure_space(pdf, space, y - 16, "REPORT")
        if ridx % 2 == 0:
            pdf.setFillColor(WHITE)
            pdf.roundRect(MARGIN, y - 12, CONTENT_W, 14, 3, fill=1, stroke=0)
        pdf.setFillColor(SLATE)
        pdf.setFont("Helvetica", 8)
        for i, cell in enumerate(row):
            if i == col_count - 1:
                pdf.drawRightString(MARGIN + (i + 1) * col_w - 6, y - 2, str(cell))
            else:
                pdf.drawString(MARGIN + i * col_w + 6, y - 2, str(cell))
        y -= 14

    _draw_footer(pdf, space, "Inventory report")
