name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan -H ${{ vars.VPS_HOST }} >> ~/.ssh/known_hosts

          ssh -vvv -i ~/.ssh/key ${{ secrets.VPS_USER }}@${{ vars.VPS_HOST }} "id && whoami && pwd && ls -la ~"
